name: canary
on:
  push:
    branches: [main]

jobs:
  canary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      
      # changelogen --canary creates a version like 0.1.2-canary.timestamp.hash
      - name: Publish Canary
        run: npx changelogen@latest --canary --publish --publishTag canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}